/*
 * This source file was generated by the Gradle 'init' task
 */
package dnd.hippolinc.dmstuff;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
    //Monster cyan = new Monster("cyan", "clubs", 1, 0);

    Scanner input = new Scanner(System.in);  // Create a Scanner object
    System.out.println("Enter a suit");

    String suit = input.nextLine();  // Read user input
    }
}
